// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deposit_funding_inputs.sql

package sqlc

import (
	"context"
)

const InsertDepositFundingInput = `-- name: InsertDepositFundingInput :exec
INSERT INTO ledger_deposit_funding_inputs (
    input_hash, input_index, deposit_hash, deposit_index, created_at
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (input_hash, input_index, deposit_hash, deposit_index)
DO NOTHING
`

type InsertDepositFundingInputParams struct {
	InputHash    []byte
	InputIndex   int32
	DepositHash  []byte
	DepositIndex int32
	CreatedAt    int64
}

// InsertDepositFundingInput records one previous outpoint a boarding
// deposit's funding transaction spent. Crash-replay safe: the durable ledger
// mailbox replays unprocessed messages on startup, so a re-delivered deposit
// re-inserts the same rows and must not fail.
func (q *Queries) InsertDepositFundingInput(ctx context.Context, arg InsertDepositFundingInputParams) error {
	_, err := q.db.ExecContext(ctx, InsertDepositFundingInput,
		arg.InputHash,
		arg.InputIndex,
		arg.DepositHash,
		arg.DepositIndex,
		arg.CreatedAt,
	)
	return err
}

const ListDepositsFundedByInput = `-- name: ListDepositsFundedByInput :many
SELECT deposit_hash, deposit_index
FROM ledger_deposit_funding_inputs
WHERE input_hash = $1
  AND input_index = $2
ORDER BY deposit_hash, deposit_index
`

type ListDepositsFundedByInputParams struct {
	InputHash  []byte
	InputIndex int32
}

type ListDepositsFundedByInputRow struct {
	DepositHash  []byte
	DepositIndex int32
}

// ListDepositsFundedByInput returns the boarding deposits an outpoint is
// recorded as funding. An own-wallet proceeds row arriving after the deposit
// it funded uses this to discover that it must reverse its own credit, and to
// find the deposit whose confirmation height stamps that reversal, so the leg
// is byte-identical whichever message books it.
func (q *Queries) ListDepositsFundedByInput(ctx context.Context, arg ListDepositsFundedByInputParams) ([]ListDepositsFundedByInputRow, error) {
	rows, err := q.db.QueryContext(ctx, ListDepositsFundedByInput, arg.InputHash, arg.InputIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDepositsFundedByInputRow
	for rows.Next() {
		var i ListDepositsFundedByInputRow
		if err := rows.Scan(&i.DepositHash, &i.DepositIndex); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
