// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deposit_funding_inputs.sql

package sqlc

import (
	"context"
)

const CountDepositFundingInput = `-- name: CountDepositFundingInput :one
SELECT CAST(COUNT(*) AS BIGINT) AS input_count
FROM ledger_deposit_funding_inputs
WHERE input_hash = $1
  AND input_index = $2
`

type CountDepositFundingInputParams struct {
	InputHash  []byte
	InputIndex int32
}

// CountDepositFundingInput reports whether an outpoint is recorded as the
// funding input of any boarding deposit. An own-wallet proceeds row arriving
// after the deposit it funded uses this to discover that it must reverse its
// own credit.
func (q *Queries) CountDepositFundingInput(ctx context.Context, arg CountDepositFundingInputParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountDepositFundingInput, arg.InputHash, arg.InputIndex)
	var input_count int64
	err := row.Scan(&input_count)
	return input_count, err
}

const InsertDepositFundingInput = `-- name: InsertDepositFundingInput :exec
INSERT INTO ledger_deposit_funding_inputs (
    input_hash, input_index, deposit_hash, deposit_index, created_at
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (input_hash, input_index, deposit_hash, deposit_index)
DO NOTHING
`

type InsertDepositFundingInputParams struct {
	InputHash    []byte
	InputIndex   int32
	DepositHash  []byte
	DepositIndex int32
	CreatedAt    int64
}

// InsertDepositFundingInput records one previous outpoint a boarding
// deposit's funding transaction spent. Crash-replay safe: the durable ledger
// mailbox replays unprocessed messages on startup, so a re-delivered deposit
// re-inserts the same rows and must not fail.
func (q *Queries) InsertDepositFundingInput(ctx context.Context, arg InsertDepositFundingInputParams) error {
	_, err := q.db.ExecContext(ctx, InsertDepositFundingInput,
		arg.InputHash,
		arg.InputIndex,
		arg.DepositHash,
		arg.DepositIndex,
		arg.CreatedAt,
	)
	return err
}
