// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: oor_status.sql

package sqlc

import (
	"context"
)

const GetOOROutgoingStatusSnapshot = `-- name: GetOOROutgoingStatusSnapshot :one
SELECT session_id, actor_id, direction, phase, idempotency_key, status, last_error, snapshot_data, snapshot_version, flow_version, created_at, updated_at FROM oor_session_registry
WHERE session_id = $1 AND direction = 1
`

// Incoming snapshots cannot contribute outgoing input or retry diagnostics.
func (q *Queries) GetOOROutgoingStatusSnapshot(ctx context.Context, sessionID []byte) (OorSessionRegistry, error) {
	row := q.db.QueryRowContext(ctx, GetOOROutgoingStatusSnapshot, sessionID)
	var i OorSessionRegistry
	err := row.Scan(
		&i.SessionID,
		&i.ActorID,
		&i.Direction,
		&i.Phase,
		&i.IdempotencyKey,
		&i.Status,
		&i.LastError,
		&i.SnapshotData,
		&i.SnapshotVersion,
		&i.FlowVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetOORStatus = `-- name: GetOORStatus :one
SELECT session_id, direction, status, phase, last_error,
    created_at, updated_at, has_package
FROM oor_status
WHERE session_id = $1
`

func (q *Queries) GetOORStatus(ctx context.Context, sessionID []byte) (OorStatus, error) {
	row := q.db.QueryRowContext(ctx, GetOORStatus, sessionID)
	var i OorStatus
	err := row.Scan(
		&i.SessionID,
		&i.Direction,
		&i.Status,
		&i.Phase,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HasPackage,
	)
	return i, err
}

const ListOORStatus = `-- name: ListOORStatus :many
WITH registry AS (
SELECT r.session_id, r.direction, r.status, r.phase, r.last_error, r.created_at, r.updated_at, r.has_package FROM oor_registry_status r
WHERE r.created_at <= $2
    AND (r.created_at < $2 OR r.session_id < $3)
    AND (CAST($4 AS INTEGER) = 0 OR r.direction = $4)
    AND (CAST($5 AS INTEGER) = -1 OR r.status = $5)
ORDER BY r.created_at DESC, r.session_id DESC
LIMIT CAST($1 AS BIGINT)
), package_floor AS (
SELECT CASE WHEN COUNT(*) = $1 THEN MIN(created_at)
    ELSE CAST(-9223372036854775808 AS BIGINT) END AS created_at FROM registry
), packages AS (
SELECT p.session_id, p.direction, p.status, p.phase, p.last_error, p.created_at, p.updated_at, p.has_package FROM oor_package_status p
WHERE p.created_at >= (SELECT created_at FROM package_floor)
    AND p.created_at <= $2
    AND (p.created_at < $2 OR p.session_id < $3)
    AND (CAST($4 AS INTEGER) = 0 OR p.direction = $4)
    AND (CAST($5 AS INTEGER) = -1 OR p.status = $5)
ORDER BY p.created_at DESC, p.session_id DESC
LIMIT CAST($1 AS BIGINT)
)
SELECT session_id, direction, status, phase, last_error, created_at, updated_at, has_package FROM packages
UNION ALL
SELECT session_id, direction, status, phase, last_error, created_at, updated_at, has_package FROM registry
ORDER BY created_at DESC, session_id DESC
LIMIT CAST($1 AS BIGINT)
`

type ListOORStatusParams struct {
	PageLimit       int64
	BeforeCreatedAt int64
	BeforeID        []byte
	DirectionFilter int32
	StatusFilter    int32
}

type ListOORStatusRow struct {
	SessionID  []byte
	Direction  int32
	Status     int32
	Phase      string
	LastError  string
	CreatedAt  int64
	UpdatedAt  int64
	HasPackage int32
}

// Bound both ordered sources before the final merge, including SQLite where
// an outer LIMIT alone would sort the entire UNION result.
// A full registry page already outranks every older package. Keep timestamp
// ties for the ID tie-breaker; a partial page must still search older history.
func (q *Queries) ListOORStatus(ctx context.Context, arg ListOORStatusParams) ([]ListOORStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, ListOORStatus,
		arg.PageLimit,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.DirectionFilter,
		arg.StatusFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOORStatusRow
	for rows.Next() {
		var i ListOORStatusRow
		if err := rows.Scan(
			&i.SessionID,
			&i.Direction,
			&i.Status,
			&i.Phase,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HasPackage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
