// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: owned_wallet_scripts.sql

package sqlc

import (
	"context"
)

const CountOwnedWalletScript = `-- name: CountOwnedWalletScript :one
SELECT CAST(COUNT(*) AS BIGINT) AS script_count
FROM owned_wallet_scripts
WHERE pk_script = $1
`

// CountOwnedWalletScript reports whether a pkScript is in the registry.
// Absent means "not known to be ours", which is the conservative answer.
func (q *Queries) CountOwnedWalletScript(ctx context.Context, pkScript []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountOwnedWalletScript, pkScript)
	var script_count int64
	err := row.Scan(&script_count)
	return script_count, err
}

const UpsertOwnedWalletScript = `-- name: UpsertOwnedWalletScript :exec
INSERT INTO owned_wallet_scripts (pk_script, source, created_at)
VALUES ($1, $2, $3)
ON CONFLICT (pk_script) DO NOTHING
`

type UpsertOwnedWalletScriptParams struct {
	PkScript  []byte
	Source    string
	CreatedAt int64
}

// UpsertOwnedWalletScript records a backing-wallet script the daemon minted.
// Minting is idempotent from the registry's point of view: re-recording the
// same script is a no-op, and the first source recorded wins so a script's
// provenance never changes underneath an operator reading the table.
func (q *Queries) UpsertOwnedWalletScript(ctx context.Context, arg UpsertOwnedWalletScriptParams) error {
	_, err := q.db.ExecContext(ctx, UpsertOwnedWalletScript, arg.PkScript, arg.Source, arg.CreatedAt)
	return err
}
